language: python
sudo: false
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -e .
  - python scripts/test_setup.py
# command to run tests, e.g. python setup.py test
script: py.test tests
